apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base layer: defines all resources in their canonical form.
# Overlays (k8s/overlays/dev/) patch on top of this.

namespace: devsecops-project

resources:
  - namespace.yaml
  # Backend
  - backend/deployment.yaml
  - backend/service.yaml
  # Frontend
  - frontend/nginx-config.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - frontend/ingress.yaml
  # Database
  - database/pvc.yaml
  - database/statefulset.yaml
  - database/service.yaml

# Common labels applied to every resource in this base
commonLabels:
  app.kubernetes.io/part-of: devsecops-project
